BASE:
  MODEL: 'TEXTNET'
  TYPE: 'D'
  VERSION: 'v1'
  ENV: 'EnvironmentName'
  TASK_ID: 12345
  NETWORK: 'vgg'
  NUM_GPUS: 1
  GPU_ID: '3,'
  WORKERS: 4
  CUDA: True
  DEVICE: 'cuda:0'

DATASETS:
  DATASET: 'TotalText'
  TYPE: 'DataType'
ADDRESS:
  ALPHABET: ''
  TRAIN_DATA_DIR: '/home/shf/fudan_ocr_system/datasets/ICDAR19/'
  TRAIN_GT_DIR: '/home/shf/fudan_ocr_system/datasets/ICDAR19/'
  VAL_DATA_DIR: '/home/shf/fudan_ocr_system/datasets/ICDAR19/'
  VAL_GT_DIR: '/home/shf/fudan_ocr_system/datasets/ICDAR19/'
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  GT_JSON_DIR: '/home/shf/fudan_ocr_system/datasets/ICDAR19/test_labels.json'
  CHECKPOINTS_DIR: './Checkpoints/'
  PRETRAIN_MODEL_DIR: ''
  RESULT_DIR: './Output/'
  CACHE_DIR: ''
  LOGGER_DIR: './Logger/'

IMAGE:
  IMG_H: 32
  IMG_W: 100
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 8
  LR: 0.0001
  DECAY_RATE: 0.1
  OPTIMIZER: 'Adam'
  LOSS: 'TextLoss'
  DYNAMIC_LR: False
  DETAILS:
    HIDDEN_LAYER: 10

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 3000
  SHOW_FREQ: 100
  VAL_FREQ: 1000

targetH: 32
targetW: 100
BidirDecoder: True
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True

TEXTSNAKE:
  input_size: 512
  exp_name: 'example1'
  output_channel: 7

  # train opts
  start_iter: 0
  max_iters: 50000
  lr_adjust: 'fix'
  stepvalues: []
  weight_decay: '0.'
  wd: '0.'
  gamma: 0.1
  momentum: 0.9

  # data args
  rescale: 255.0
  means: [0.474, 0.445, 0.418]
  stds: [1., 1., 1.]

