MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  #TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  #TEST: ("coco_2014_minival",)
  TRAIN: ("ICDAR2013Dataset", )
  TEST: ("ICDAR2013Dataset",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  #STEPS: (120000, 160000)
  STEPS: (20000, 60000)
  MAX_ITER: 80000
  IMS_PER_BATCH: 2

OUTPUT_DIR: './models/fasterrcnn-IC13-E2E/'
