train_nips: '/home/chenjingye/datasets/ic03_train_lmdb'
train_cvpr: ''
valroot: '/home/chenjingye/datasets/ic03_train_lmdb'
workers: 2
batchSize: 64
imgH: 64
imgW: 200
targetH: 32
targetW: 100
nh: 256
niter: 10
lr: 0.01
cuda: true
ngpu: 1
MORAN: ''
alphabet: ':e:l:f:a:d:h:i:v:r:b:3:6:8:9:m:c:2:5:0:o:n:N:t:w:G:R:E:K:A:S:T:O:M:Y:C:W:I:L:U:B:P:F:V:D:7:H:y:g:p:u:J:-:k:4:1:j:Z:.:X:x:!:(:&:q:;:):?:£:é:::Q:Ñ:É:$'
sep: ':'
experiment: None
displayInterval: 100
n_test_disp: 10
valInterval: 1000
saveInterval: 40000
adam: false
beta1: 0.5
adadelta: true
sgd: false
BidirDecoder: frue


