model: 'AdvancedEAST' # BASE.MODEL
task_id: '3T1280'  # BASE.TASK_ID
train_size: 1280 #
size_group: [512, 640, 768, 896, 1024, 1280, 1408, 1536, 1920] #

dset_name: 'ICADR15' # DATASETS.DATASET
train_img: '/home/msy/datasets/ICDAR15/Text_Localization/train/img/'  # ADDRESS.DETECTION.TRAIN_DATA_DIR
train_gt: '/home/msy/datasets/ICDAR15/Text_Localization/train/gt/'  # ADDRESS.DETECTION.TRAIN_GT_DIR
val_img: '/home/msy/datasets/ICDAR15/Text_Localization/val/img/'  # ADDRESS.DETECTION.VAL_DATA_DIR
val_gt: '/home/msy/datasets/ICDAR15/Text_Localization/val/gt/'  # ADDRESS.DETECTION.VAL_GT_DIR

# num_process: max(os.cpu_count() - 2, os.cpu_count() // 2)
num_process: 1  # BASE.WORKERS
cache_dir: './cache/'  # ADDRESS.CACHE_DIR
result_dir: '/home/msy/AdvancedEAST1/result'  # ADDRESS.RESULT_DIR

batch_size_group: [15, 10, 6, 4, 4, 2, 1, 1, 1]
batch_size_per_gpu: 1  # MODEL.BATCH_SIZE
# batch_size_per_gpu: batch_size_group[size_group.index(train_size)]

gpu_ids: [0, 1]  # BASE.GPU_ID

lr_rate: 0.0001  # MODEL.LR
decay_step: 45  # MODEL.DECAY_STEP
decay_rate: 0.1  # MODEL.DECAY_RATE

max_epoch: 50  # MODEL.EPOCH
patience: 5 # MODEL.PATIENCE
print_step: 270  # SHOW_FREQ

num_workers: 4  # BASE.WORKERS
init_type: 'xavier'

lambda_inside_score_loss: 4.0
lambda_side_vertex_code_loss: 1.0
lambda_side_vertex_coord_loss: 1.0

shrink_ratio: 0.2
shrink_side_ratio: 0.6
epsilon: 1e-4

pixel_size: 4

gt_json_path: '/home/msy/datasets/ICDAR15/Text_Localization/val/res.json' # ADDRESS.DETECTION.GT_JSON_DIR
iou_threshold: 0.5

pixel_threshold: 0.9
side_vertex_pixel_threshold: 0.9
trunc_threshold: 0.1
predict_cut_text_line: False

draw: 'store_true'