model: 'EAST'
test_data_path: '/home/cjy/EAST/icdar2015/ch4_test_images'
test_gt_path: '/home/cjy/EAST/icdar2015/Challenge4_Test_Task1_GT'
gpu_list: '2'
checkpoint_path: '/home/cjy/east_icdar2015_resnet_v1_50_rbox'
json_output: './temp.json'
json_output_gt: './temp_gt.json'
output_dir: './cjytest'
no_write_images: false
text_scale: 512
