model: 'EAST'
input_size: 512
batch_size_per_gpu: 14
num_readers: 16
learning_rate: 0.0001
max_steps: 20000
moving_average_decay: 0.997
gpu_list: '3'
checkpoint_path: '/home/cjy/east_icdar2015_resnet_v1_50_rbox/'
restore: false
save_checkpoint_steps: 2000
save_summary_steps: 100
pretrained_model_path: '/home/cjy/resnet_v1_50_2016_08_28/resnet_v1_50.ckpt'
dataset: 'icdar2015'
training_data_path: '/home/cjy/EAST/icdar2015/ch4_training_images/'
training_gt_path: '/home/cjy/EAST/icdar2015/ch4_training_localization_transcription_gt/'
max_image_large_side: 1280
max_text_size: 800
min_text_size: 10
min_crop_side_ratio: 0.1
geometry: 'RBOX'
text_scale: 512


