model: 'GRCNN'
TRAIN:
        BATCH_SIZE: 16
        IMG_H: 32
        MAX_W: 280
        LR: 0.0001
        BETA1: 0.5
        DATA_SOURCE:
                TYPE: "IMG_DATA"
                #IMG_ROOT: "/home/cjy/Word_recognition/ch4_training_word_images_gt/"
                #TRAIN_SET: "/home/cjy/Word_recognition/train_label.txt" #path for train dataset
                IMG_ROOT: "/home/cjy/mnt/ramdisk/max/90kDICT32px/"
                TRAIN_SET: "/home/cjy/image_label_pair.txt" #path for train dataset
VALIDATION:
  # IC03
  # IMG_ROOT: '/home/cjy/ICDAR2003/WordR/TrialTest/'
  # VAL_SET: '/home/cjy/ICDAR2003/WordR/TrialTest/target.txt'


  # IC13
  # IMG_ROOT: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/'
  # VAL_SET: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/Challenge2_Test_Task3_GT.txt'

        # IC15
        IMG_ROOT: "/home/cjy/Word_recognition/ch4_test_word_images_gt"
        VAL_SET: "/home/cjy/Word_recognition/Challenge4_Test_Task3_GT.txt" #path for validation dataset
EPOCHS: 3000
STEP: 20
LOG_FREQ: 50
SAVE_FREQ: 1
SAVE_PATH: "./checkpoints_9000k/"  #path for model
CUDA: True
WORKERS: 4
OPTIMIZER: "Adam"
LOGGER_PATH: "./logger/"  #path for logger
VAL_ONLY: FALSE
FINETUNE: FALSE
RESUME: FALSE
CRANN: ""
N_GPU: 1
#CRANN: "./checkpoints/crann_15_9.pth"


CNN: 
    MODEL: "grcnn"
RNN:
    MODEL: "compositelstm"
    n_In: 512
    n_Hidden: 256
    n_Layer: "Number: for multi layer lstm."
    multi_gpu: none

DEMO:
  test_set_image: ''
  test_set_mapping: './art_test.txt'
  test_set_lmdb: '/home/cjy/ic03_test_lmdb'
  model_path: '/home/cjy/grcnn/checkpoints/crann_11_1.pth'