BASE:
  MODEL: 'CRNN'
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '2,'
  WORKERS: 4
  CUDA: True

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'custom'
  SAMPLER: 'Random_Sequential'
  COLLATE_FN: ''

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/words/grcnn.txt'
  TRAIN_DATA_DIR: '/home/cjy/mnt/ramdisk/max/90kDICT32px/'
  TRAIN_GT_DIR: '/home/cjy/image_label_pair.txt'
#  TRAIN_DATA_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/'
#  TRAIN_GT_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/Challenge2_Test_Task3_GT.txt'
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/'
  VAL_GT_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/Challenge2_Test_Task3_GT.txt'
  CHECKPOINTS_DIR: './CRNN_LSVT_Checkpoints_usetransform/'
  PRETRAIN_MODEL_DIR: ''
  LOGGER_DIR: './CRNN_Logger_usetransform/'

IMAGE:
  IMG_H: 32
  IMG_W: 100
  IMG_CHANNEL: 3

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

VISUALIZE:
  #the tag to indentify log file, starts with 'Logger/'
  TAG: 'Logger/runs/exp-1'

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 16
  LR: 1.0
  DYNAMIC_LR: False
  OPTIMIZER: 'Adadelta'
  LOSS: 'CTCLoss'

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 4000
  SHOW_FREQ: 100
  VAL_FREQ: 1000


