BASE:
  MODEL: 'ModelName'
  VERSION: 'ModelVersion'
  ENV: 'EnvironmentName'
  TASK_ID: 12345
  NETWORK: 'NetworkName'
  NUM_GPUS: 1
  GPU_ID: '2,'
  WORKERS: 4

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'DataType'

ADDRESS:
  DETECTION:
    TRAIN_DATA_DIR: './Train/Data/'
    TRAIN_GT_DIR: './Train/GT/'
    TEST_DATA_DIR: './Test/Data/'
    TEST_GT_DIR: './Test/GT/'
    VAL_DATA_DIR: './Val/Data/'
    VAL_GT_DIR: './Val/GT/'
  RECOGNITION:
    ALPHABET: '/home/cjy/FudanOCR/alphabet/ic15_words.txt'
    TRAIN_DATA_DIR: "/home/cjy/ic15_test_lmdb"
    TRAIN_LABEL_DIR: "/home/cjy/image_label_pair.txt"
    TEST_DATA_DIR: "/home/cjy/ic15_test_lmdb"
    TEST_LABEL_DIR: "/home/cjy/Word_recognition/Challenge4_Test_Task3_GT.txt"
    VAL_DATA_DIR: '/home/cjy/ic15_test_lmdb'
    VAL_LABEL_DIR: './Val/Label/'
  CHECKPOINTS_DIR: './Checkpoints/'
  PRETRAIN_MODEL_DIR: './Pretrain_model/'
  CACHE_DIR: './Cache/'
  LOGGER_DIR: './Logger/'

IMAGE:
  IMG_H: 32
  IMG_W: 280
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 16
  LR: 0.0001
  DECAY_RATE: 0.1
  OPTIMIZER: 'Adam'
  LOSS: 'CrossEntropyLoss'
  DETAILS:
    HIDDEN_LAYER: 10

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

SAVE_FREQ: 1
SHOW_FREQ: 50
VAL_FREQ: 1000

targetH: 32
targetW: 100
BidirDecoder: False
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True


CNN:
    MODEL: "grcnn"
RNN:
    MODEL: "compositelstm"
    n_In: 512
    n_Hidden: 256
    n_Layer: "Number: for multi layer lstm."
    multi_gpu: none

