BASE:
  MODEL: 'GRCNN'
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '0,'
  WORKERS: 4

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'custom'
  SAMPLER: 'Random_Sequential'
  COLLATE_FN: ''

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/words/grcnn.txt'
#  TRAIN_DATA_DIR: '/home/cjy/mnt/ramdisk/max/90kDICT32px/'
#  TRAIN_GT_DIR: '/home/cjy/image_label_pair.txt'
  TRAIN_DATA_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/'
  TRAIN_GT_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/Challenge2_Test_Task3_GT.txt'
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/'
  VAL_GT_DIR: '/home/cjy/ICDAR2013/Challenge2_Test_Task3_Images/Challenge2_Test_Task3_GT.txt'
  CHECKPOINTS_DIR: './GRCNN_LSVT_Checkpoints/'
  PRETRAIN_MODEL_DIR: ''
  LOGGER_DIR: './GRCNN_Logger/'

IMAGE:
  IMG_H: 32
  IMG_W: 280
  IMG_CHANNEL: 3

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 8
  LR: 0.0001
  DECAY_RATE: 0.1
  DYNAMIC_LR: False
  OPTIMIZER: 'Adam'
  LOSS: 'CTCLoss'
  DETAILS:
    HIDDEN_LAYER: 10

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 4000
  SHOW_FREQ: 100
  VAL_FREQ: 1000

BidirDecoder: False
CUDA: True

CNN:
    MODEL: "grcnn"
RNN:
    MODEL: "compositelstm"
    n_In: 512
    n_Hidden: 256
    n_Layer: "Number: for multi layer lstm."
    multi_gpu: none

