BASE:
  MODEL: 'MORAN'
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '2,'
  WORKERS: 4

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'Imdb'

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/words/ic15_words.txt'
  TRAIN_DATA_DIR: '/home/cjy/syn90_train_100000data_lmdb'
  TRAIN_GT_DIR: ''
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/ic15_test_lmdb'
  VAL_GT_DIR: ''
  CHECKPOINTS_DIR: './MORAN_Checkpoints/'
  PRETRAIN_MODEL_DIR: './pretrain_MORAN/'
  CACHE_DIR: './Cache/'
  LOGGER_DIR: './Logger/'

IMAGE:
  IMG_H: 32
  IMG_W: 100
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: True

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 64
  LR: 1.0
  DECAY_RATE: 0.1
  DYNAMIC_LR: True
  OPTIMIZER: 'Adadelta'
  LOSS: 'CrossEntropyLoss'
  DETAILS:
    HIDDEN_LAYER: 10

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 3000
  SHOW_FREQ: 100
  VAL_FREQ: 1000


targetH: 32
targetW: 100
BidirDecoder: True
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True
