BASE:
  MODEL: 'MORAN'
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '1,'
  WORKERS: 4
  CUDA: True

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'Lmdb'
  SAMPLER: ''
  COLLATE_FN: ''

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/words/lsvt_train_words.txt'
  TRAIN_DATA_DIR: '/home/cjy/xuxixidatasets/LSVT_train'
  TRAIN_GT_DIR: ''
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/xuxixidatasets/LSVT_test'
  VAL_GT_DIR: ''
  CHECKPOINTS_DIR: './MORAN_LSVT_Checkpoints/'
  PRETRAIN_MODEL_DIR: './MORAN_PRETRAIN'
  LOGGER_DIR: './MORAN_Logger/'

IMAGE:
  IMG_H: 64
  IMG_W: 200
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 64
  LR: 1.0
  DECAY_RATE: 0.1
  DYNAMIC_LR: False
  OPTIMIZER: 'Adadelta'
  LOSS: 'CrossEntropyLoss'
  DETAILS:
    HIDDEN_LAYER: 10

VISUALIZE:
  #the tag to indentify log file, starts with 'Logger/'
  TAG: 'Logger/runs/exp-1'

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 3000
  SHOW_FREQ: 100
  VAL_FREQ: 200

nh: 256
targetH: 32
targetW: 100
BidirDecoder: True
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True
