# python main.py --config_file ./config/recognition/MORAN.yaml
BASE:
  MODEL: 'MORAN'
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '1,'
  WORKERS: 4
  CUDA: True
  EXPERIMENT_NAME:  'MORAN_mjq2'

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'lmdb'
  SAMPLER: ''
  COLLATE_FN: ''

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/words/ic15_words.txt'
  TRAIN_DATA_DIR: '/home/cjy/syn90_train_9000000data_lmdb'
  TRAIN_GT_DIR: ''
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/mjq/mjqlmdb'
  VAL_GT_DIR: ''
  CHECKPOINTS_DIR: './IC13_Checkpoints/'
  PRETRAIN_MODEL_DIR: './MORAN'
  LOGGER_DIR: './IC13_Logger/'

IMAGE:
  IMG_H: 64
  IMG_W: 200
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: True
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 64
  LR: 1.0
  DYNAMIC_LR: False
  OPTIMIZER: 'Adadelta'
  LOSS: 'CrossEntropyLoss'


VISUALIZE:
  #the tag to indentify log file, starts with 'Logger/'
  TAG: 'Logger/runs/exp-1'
  RECOGNITION_VISUALIZE: True

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 3000
  SHOW_FREQ: 100
  VAL_FREQ: 1000

nh: 256
targetH: 32
targetW: 100
BidirDecoder: True
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True
fp: 0
