model: 'AdvancedEAST'
task_id: '3T1280'
train_size: int(task_id[2:])

dset_name: 'ICADR15'
train_img: '/home/msy/datasets/ICDAR15/Text_Localization/train/img/'
train_gt: '/home/msy/datasets/ICDAR15/Text_Localization/train/gt/'
val_img: '/home/msy/datasets/ICDAR15/Text_Localization/val/img/'
val_gt: '/home/msy/datasets/ICDAR15/Text_Localization/val/gt/'

num_process: max(os.cpu_count() - 2, os.cpu_count() // 2)
cache_dir: './cache/'
result_dir: './result/'

batch_size_group: [15, 10, 6, 4, 4, 2, 1, 1, 1]
batch_size_per_gpu: 2
# batch_size_per_gpu: batch_size_group[size_group.index(train_size)]

gpu_ids: [0, 1]

lr_rate: 0.0001
decay_step: 45
decay_rate: 0.1

max_epoch: 50
patience: 5
print_step: 270

num_workers: 4
init_type: 'xavier'

lambda_inside_score_loss: 4.0
lambda_side_vertex_code_loss: 1.0
lambda_side_vertex_coord_loss: 1.0

shrink_ratio: 0.2
shrink_side_ratio: 0.6
epsilon: 1e-4

pixel_size: 4

gt_json_path: '/home/msy/datasets/ICDAR15/Text_Localization/val/res.json'
iou_threshold: 0.5

pixel_threshold: 0.9
side_vertex_pixel_threshold: 0.9
trunc_threshold: 0.1
predict_cut_text_line: False