BASE:
  MODEL: 'MORAN'
  # [Option] R(recognition)/D(detection)
  TYPE: 'R'
  NUM_GPUS: 1
  GPU_ID: '2,'
  WORKERS: 4
  CUDA: True

DATASETS:
  DATASET: 'DatasetName'
  # [Option] Imdb(moran)/custom_dset(AEAST)/total_text(textsnake)/icdar(maskrcnnbenchmark)/CTW1500(psenet)/...
  TYPE: 'Imdb'
  # [Option] Random_Sequential / Random / Sequential / None
  SAMPLER: 'Random_Sequential'
  COLLATE_FN: ''

ADDRESS:
  ALPHABET: '/home/cjy/FudanOCR/alphabet/ic15_words.txt'
  TRAIN_DATA_DIR: '/home/cjy/syn90_train_100000data_lmdb'
  TRAIN_GT_DIR: ''
  TEST_DATA_DIR: ''
  TEST_GT_DIR: ''
  VAL_DATA_DIR: '/home/cjy/ic15_test_lmdb'
  VAL_GT_DIR: ''
  CHECKPOINTS_DIR: './MORAN_Checkpoints/'
  PRETRAIN_MODEL_DIR: './pretrain_MORAN/'
  LOGGER_DIR: './Logger/'
  # If opt.BASE.TYPE == 'D', you need to fill in the following parameters
  DET_RESULT_DIR : ''
  GT_JSON_DIR: ''

IMAGE:
  IMG_H: 32
  IMG_W: 100
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 64
  LR: 1.0
  DYNAMIC_LR: False
  # [Option] Adadelta/Adam/...
  OPTIMIZER: 'Adadelta'
  # [Option] MSELoss/CrossEntropyLoss/CTCLoss/TextLoss/AEASTLOSS/...
  LOSS: 'CrossEntropyLoss'

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

FREQ:
  SAVE_FREQ: 3000
  SHOW_FREQ: 100
  VAL_FREQ: 1000

VISUALIZE:
  #the tag to indentify log file, starts with 'Logger/'
  TAG: 'Logger/runs/exp-1'

# your own parameters
MORAN:
  TARGET_H: 32
  TARGET_W: 100
