BASE:
  MODEL: 'MORAN'
  TYPE: 'R'
  VERSION: 'ModelVersion'
  ENV: 'EnvironmentName'
  TASK_ID: 12345
  NETWORK: 'NetworkName'
  NUM_GPUS: 1
  GPU_ID: '2,'
  WORKERS: 4

DATASETS:
  DATASET: 'DatasetName*'
  TYPE: 'DataType'

ADDRESS:
  DETECTION:
    TRAIN_DATA_DIR: './Train/Data/'
    TRAIN_GT_DIR: './Train/GT/'
    TEST_DATA_DIR: './Test/Data/'
    TEST_GT_DIR: './Test/GT/'
    VAL_DATA_DIR: './Val/Data/'
    VAL_GT_DIR: './Val/GT/'
  RECOGNITION:
    ALPHABET: '/home/cjy/FudanOCR/alphabet/ic15_words.txt'
    TRAIN_DATA_DIR: '/home/cjy/syn90_train_100000data_lmdb'
    TRAIN_LABEL_DIR: ''
    TEST_DATA_DIR: '/home/cjy/ic15_test_lmdb'
    TEST_LABEL_DIR: ''
    VAL_DATA_DIR: ''
    VAL_LABEL_DIR: ''
  CHECKPOINTS_DIR: './MORAN_Checkpoints/'
  PRETRAIN_MODEL_DIR: './pretrain_MORAN/'
  CACHE_DIR: './Cache/'
  LOGGER_DIR: './Logger/'

IMAGE:
  IMG_H: 32
  IMG_W: 100
  IMG_CHANNEL: 1

FUNCTION:
  VAL_ONLY: False
  FINETUNE: False

MODEL:
  EPOCH: 100000
  BATCH_SIZE: 64
  LR: 1.0
  DECAY_RATE: 0.1
  OPTIMIZER: 'Adadelta'
  LOSS: 'CrossEntropyLoss'
  DETAILS:
    HIDDEN_LAYER: 10

THRESHOLD:
  MAXSIZE: 100
  MINSIZE: 1
  TEXT_SCALE: 75

SAVE_FREQ: 3000
SHOW_FREQ: 100
VAL_FREQ: 1000

targetH: 32
targetW: 100
BidirDecoder: True
inputDataType: 'torch.cuda.FloatTensor'
maxBatch: 256
CUDA: True
