model: 'maskscoring_rcnn'
OUTPUT_DIR: 'models/'
PATHS_CATALOG: '/home/shf/FudanOCR/detection_model\maskscoring_rcnn\maskrcnn_benchmark\config\paths_catalog.py'
MODEL:
  META_ARCHITECTURE: 'GeneralizedRCNN'
  WEIGHT: 'catalog://ImageNetPretrained/MSRA/R-50'
  PRETRAINED_MODELS: 'pretrained_models'
  RPN_ONLY: False
  MASK_ON: True
  MASKIOU_ON: True
  DEVICE: 'cuda'
  MASKIOU_LOSS_WEIGHT: 1.0
  BACKBONE:
    CONV_BODY: 'R-50-FPN'
    OUT_CHANNELS: 256
    FREEZE_CONV_BODY_AT: 2
  RPN:
    USE_FPN: True
    RPN_HEAD: 'SingleConvRPNHead'
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    STRADDLE_THRESH: 0
    FG_IOU_THRESHOLD: 0.7
    BG_IOU_THRESHOLD: 0.3
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
    NMS_THRESH: 0.7
    MIN_SIZE: 0
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.5
    BBOX_REG_WEIGHTS: (10., 10., 5., 5.)
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.05
    NMS: 0.5
    DETECTIONS_PER_IMG: 100
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    NUM_CLASSES: 81
    MLP_HEAD_DIM: 1024
    FEATURE_EXTRACTOR: 'FPN2MLPFeatureExtractor'
    PREDICTOR: 'FPNPredictor'
  ROI_MASK_HEAD:
    FEATURE_EXTRACTOR: 'MaskRCNNFPNFeatureExtractor'
    PREDICTOR: 'MaskRCNNC4Predictor'
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    MLP_HEAD_DIM: 1024
    CONV_LAYERS: (256, 256, 256, 256)
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    POSTPROCESS_MASKS: False
    POSTPROCESS_MASKS_THRESHOLD: 0.5
  RESNETS:
    WIDTH_PER_GROUP: 64
    STRIDE_IN_1X1: True
    TRANS_FUNC: 'BottleneckWithFixedBatchNorm'
    STEM_FUNC: 'StemWithFixedBatchNorm'
    RES5_DILATION: 1
    RES2_OUT_CHANNELS: 256
    STEM_OUT_CHANNELS: 64
INPUT:
  MIN_SIZE_TRAIN: 800
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  PIXEL_MEAN: (102.9801, 115.9465, 122.7717)
  PIXEL_STD: (1., 1., 1.)
  TO_BGR255: True
DATASETS:
  TRAIN: ('coco_2017_train',)
  TEST: ('coco_2017_val',)
DATALOADER:
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: True
SOLVER:
  GAMMA: 0.1
  WARMUP_FACTOR: 1.0 / 3
  WARMUP_ITERS: 500
  WARMUP_METHOD: 'linear'
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 18
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
  STEPS: (60000, 80000)
  MAX_ITER: 80000
TEST:
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1
local_rank: 0
skip-test: False
distributed: False