model: 'MORAN_V2_xuxixi'
train_nips: '/home/cjy/ic13_test_lmdb'
train_cvpr: ''
valroot: '/home/cjy/ic13_test_lmdb'
workers: 4
batchSize: 64
imgH: 64
imgW: 200
targetH: 32
targetW: 100
nh: 256
niter: 10
lr: 0.01
cuda: true
ngpu: 1
MORAN: ''
alphabet: '0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:g:h:i:j:k:l:m:n:o:p:q:r:s:t:u:v:w:x:y:z:$'
sep: ':'
experiment: None
displayInterval: 100
n_test_disp: 10
valInterval: 1000
saveInterval: 40000
adam: false
beta1: 0.5
adadelta: true
sgd: false
BidirDecoder: frue
