MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  PRETRAINED_MODELS: 'pretrained_models'
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2500
    PRE_NMS_TOP_N_TEST: 1500
    POST_NMS_TOP_N_TEST: 1200
    FPN_POST_NMS_TOP_N_TEST: 1200
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  MASKIOU_ON: True
DATASETS:
  TRAIN: ("LSVT_train",)
  TEST: ("LSVT_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 90000)
  MAX_ITER: 200000
INPUT:
  PIXEL_MEAN: [106.2832, 112.1224, 115.9855]
  PIXEL_STD: [0.2480, 0.2457, 0.2528]
#OUTPUT_DIR: "save/lsvt_0407/"
#SUMMARY_DIR: "summary/lsvt_0407/"
#VIS_DIR: "vis/lsvt_0407_test/"
OUTPUT_DIR: "save/lsvt_0404/"
SUMMARY_DIR: "summary/lsvt_0404/"
VIS_DIR: "vis/lsvt_0404_test/"