MODEL:
  META_ARCHITECTURE: "MaskRRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  PRETRAINED_MODELS: 'pretrained_models'
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.2, 0.5, 1.0, 2.0, 5.0)
    PRE_NMS_TOP_N_TRAIN: 2500
    PRE_NMS_TOP_N_TEST: 1500
    POST_NMS_TOP_N_TEST: 1200
    FPN_POST_NMS_TOP_N_TEST: 1200
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 128 #new 512

  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  MASKIOU_ON: False
DATASETS:
  TRAIN: ("LSVT_train", "LSVT_train_copy", "LSVT_weak_0", "LSVT_weak_1", "LSVT_weak_3", "LSVT_weak_4", "LSVT_weak_5", "LSVT_weak_6", "LSVT_weak_7", "LSVT_weak_8", )
  TEST: ("LSVT_demo",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 180000)
  MAX_ITER: 400000
  IMS_PER_BATCH: 2
INPUT:
  PIXEL_MEAN: [106.2832, 112.1224, 115.9855]
  PIXEL_STD: [1., 1., 1.]   # [0.2480, 0.2457, 0.2528]
OUTPUT_DIR: "save/lsvt_0423/"
SUMMARY_DIR: "summary/lsvt_0423/"
VIS_DIR: "vis/lsvt_0423_test/"