TRAIN:
        BATCH_SIZE: 32
        IMG_H: 32
        MAX_W: 280
        LR: 0.001
        BETA1: 0.5
        DATA_SOURCE:
                TYPE: "IMG_DATA"
                IMG_ROOT: ""
                TRAIN_SET: "/workspace/mnt/group/ocr-fd-group/zhangpeiyao/dataset/new_train.txt"
VALIDATION:
        IMG_ROOT: ""
        VAL_SET: "/workspace/mnt/group/ocr-fd-group/zhangpeiyao/dataset/new_test.txt"
EPOCHS: 30
STEP: 10
LOG_FREQ: 50
SAVE_FREQ: 10
SAVE_PATH: "/workspace/mnt/group/ocr-fd-group/zhangpeiyao/CRNN/zhang/checkpoints/test"
CUDA: True
WORKERS: 4
OPTIMIZER: "Adam"
LOGGER_PATH: "/workspace/mnt/group/ocr-fd-group/zhangpeiyao/CRNN/zhang/logger/test"
VAL_ONLY: FALSE
FINETUNE: FALSE
RESUME: FALSE
CRANN: "GRCNN/models/crann_11_1.pth"
N_GPU: 1

CNN:
    MODEL: "grcnn"
RNN:
    MODEL: "compositelstm"
    n_In: 512
    n_Hidden: 256
    n_Layer: "Number: for multi layer lstm."

