INPUT:
  MIN_SIZE_TRAIN: (640, 768, 896, 1024)
  MAX_SIZE_TRAIN: 1333

MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
    RBBOX_REG_WEIGHTS: (10., 10., 5., 5., 1.)


  RRPN:
    ASPECT_RATIOS: (0.125, 0.2, 0.5, 1.0)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_ANGLE: (-30.0, 0.0, 30.0, 60.0, 90.0, 120.0,)
    ANCHOR_SIZES: (2, 4, 8, 16, 32)
    GT_BOX_MARGIN: 1.4

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 300000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/ICDAR2019_LSVT_Trial_0.2_RFPN_4_ratios/'
