MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  #TRAIN: ("ICDAR2013Dataset", )
  #TEST: ("ICDAR2013Dataset",)
  #try ICDAR15
  TRAIN: ("ICDAR2015TRAIN", )
  TEST: ("ICDAR2015TEST",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 60000)
  MAX_ITER: 80000
  IMS_PER_BATCH: 1
