mode:
  networks: wdsr

device_mode: gpu

state_dict_path: model_dict/Deblur.pth

# corresponding to mode-networks
networks:
  wdsr:
    deblurnet:
      type: WDSRResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 9
    edgenet:
      type: HED
      parameters:
        in_dims: 3
        out_dims: 1
  resnet:
    deblurnet:
      type: CommonResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 9
    edgenet:
      type: HED
      parameters:
        in_dims: 3
        out_dims: 1