mode:
  networks: wdsr
  # select this param in @list[2, 4]
  scale_factor: 4
  # choose proper @shape(crop_size * batch_size) considering GPU memory & scale_factor
  crop_size: 256
  batch_size: 2

device_mode: gpu

state_dict_path: model_dict/OCRSR.pth

# corresponding to mode-networks
networks:
  wdsr:
    srunitnet2x1:
      type: WDSRResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 5
    srunitnet2x2:
      type: WDSRResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 5
  resnet:
    srunitnet2x1:
      type: CommonResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 5
        norm: batch
        activation: prelu
        learn_residual: true
    srunitnet2x2:
      type: CommonResNet
      parameters:
        input_nc: 3
        output_nc: 3
        n_blocks: 5
        norm: batch
        activation: prelu
        learn_residual: true